# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cybrium < Formula
  desc "Cybrium — AI-powered pentest platform CLI"
  homepage "https://cybrium.ai"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cybrium-ai/cli/releases/download/v0.1.0/cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "0adbe55f3a86e7d18dd711e1a8a8bf46993135afb94721b7e4c3cee462732840"

      define_method(:install) do
        bin.install "cybrium"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cybrium-ai/cli/releases/download/v0.1.0/cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "08aa82fcd957c5ccd3f4facf9c34e820d4c9266067095035c522c9875a2664b4"

      define_method(:install) do
        bin.install "cybrium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cybrium-ai/cli/releases/download/v0.1.0/cli_0.1.0_linux_amd64.tar.gz"
      sha256 "d77760b226602f382021b7c7cce192e6fe2a7ede56adc533aae95bf2bc065a9f"
      define_method(:install) do
        bin.install "cybrium"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cybrium-ai/cli/releases/download/v0.1.0/cli_0.1.0_linux_arm64.tar.gz"
      sha256 "66a466da871586b5ca46571d39c6af8c380a4d7129b66cad020430f60b980689"
      define_method(:install) do
        bin.install "cybrium"
      end
    end
  end

  test do
    system "#{bin}/cybrium --version"
  end
end
