# Auto-generated by cybrium-ai/cyproxy release workflow.
# Do not edit manually — changes will be overwritten on next release.
class Cyproxy < Formula
  desc "Cybrium intercepting proxy — TLS MITM, scope-aware capture, bounded replay"
  homepage "https://github.com/cybrium-ai/cyproxy"
  version "0.2.2"
  license :cannot_represent

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cybrium-ai/cyproxy/releases/download/v#{version}/cyproxy-darwin-arm64"
      sha256 "2ad0810ac7d6447f3288866740765388573943bb30da4999ccae597aac6bd7c4"
    else
      url "https://github.com/cybrium-ai/cyproxy/releases/download/v#{version}/cyproxy-darwin-amd64"
      sha256 "a21fb4ccb3528f5461ff6fd892a283689ac22fb9d42e73a6ee0fa303b7f893f2"
    end
  end

  def install
    bin_target = Hardware::CPU.arm? ? "cyproxy-darwin-arm64" : "cyproxy-darwin-amd64"
    bin.install bin_target => "cyproxy"
  end

  test do
    assert_match "cyproxy", shell_output("#{bin}/cyproxy --version")
  end
end
