# Auto-generated by cybrium-ai/cyproxy release workflow.
# Do not edit manually — changes will be overwritten on next release.
class Cyproxy < Formula
  desc "Cybrium intercepting proxy — TLS MITM, scope-aware capture, bounded replay"
  homepage "https://github.com/cybrium-ai/cyproxy"
  version "0.1.0"
  license :cannot_represent

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cybrium-ai/cyproxy/releases/download/v#{version}/cyproxy-darwin-arm64"
      sha256 "7149568fd3a3c4c2b0cd6b34135873b5f6ab4584ef4c04987e1f8afb655203a5"
    else
      url "https://github.com/cybrium-ai/cyproxy/releases/download/v#{version}/cyproxy-darwin-amd64"
      sha256 "e27eaac8cd0f93d8bbb69a01b622581585bc8a20a35d0e5020cc33e7c07708e8"
    end
  end

  def install
    bin_target = Hardware::CPU.arm? ? "cyproxy-darwin-arm64" : "cyproxy-darwin-amd64"
    bin.install bin_target => "cyproxy"
  end

  test do
    assert_match "cyproxy", shell_output("#{bin}/cyproxy --version")
  end
end
