# Auto-generated by cybrium-ai/cyproxy release workflow.
# Do not edit manually — changes will be overwritten on next release.
class Cyproxy < Formula
  desc "Cybrium intercepting proxy — TLS MITM, scope-aware capture, bounded replay"
  homepage "https://github.com/cybrium-ai/cyproxy"
  version "0.2.2"
  license :cannot_represent

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cybrium-ai/cyproxy-releases/releases/download/v#{version}/cyproxy-darwin-arm64"
      sha256 "2ad0810ac7d6447f3288866740765388573943bb30da4999ccae597aac6bd7c4"
    else
      url "https://github.com/cybrium-ai/cyproxy-releases/releases/download/v#{version}/cyproxy-darwin-amd64"
      sha256 "a21fb4ccb3528f5461ff6fd892a283689ac22fb9d42e73a6ee0fa303b7f893f2"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/cybrium-ai/cyproxy-releases/releases/download/v#{version}/cyproxy-linux-arm64"
      sha256 "2552bd184c458039ffbc80a115b83e183911e7532af567ef9c0912ec426ce92d"
    else
      url "https://github.com/cybrium-ai/cyproxy-releases/releases/download/v#{version}/cyproxy-linux-amd64"
      sha256 "06ad8ac6cacb40ad926ff4f7978a8c2a4be932df7769fba473b79dd8b6386fb0"
    end
  end

  def install
    bin_target = if OS.mac?
      Hardware::CPU.arm? ? "cyproxy-darwin-arm64" : "cyproxy-darwin-amd64"
    else
      Hardware::CPU.arm? ? "cyproxy-linux-arm64" : "cyproxy-linux-amd64"
    end
    bin.install bin_target => "cyproxy"
  end

  test do
    assert_match "cyproxy", shell_output("#{bin}/cyproxy --version")
  end
end
